### ISSUE TITLE
TypeError: '>=' not supported between instances of 'float' and 'Version'

### ISSUE THREAD

**Issue by revmischa** [ClearcodeHQ/pytest-postgresql#225]
Tried upgrading to 2.0.0 and same problem

```
    @request.addfinalizer
    def drop_database():
>       drop_postgresql_database(pg_user, pg_host, pg_port, pg_db, 11.2)

qc/test/conftest.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

user = None, host = None, port = None, db_name = 'qc_test', version = 11.2

    def drop_postgresql_database(user, host, port, db_name, version):
        """
        Drop databse in postgresql.
    
        :param str user: postgresql username
        :param str host: postgresql host
        :param str port: postgresql port
        :param str db_name: database name
        :param packaging.version.Version version: postgresql version number
        """
        conn = psycopg2.connect(user=user, host=host, port=port)
        conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
        cur = conn.cursor()
        # We cannot drop the database while there are connections to it, so we
        # terminate all connections first while not allowing new connections.
>       if version >= parse_version('9.2'):
E       TypeError: '>=' not supported between instances of 'float' and 'Version'

../../../../.virtualenvs/qc-backend-qjdNaO4n/lib/python3.7/site-packages/pytest_postgresql/factories.p:
84: TypeError                                                                                         
```

**Comment by fizyk** [comment]
Hmm.... the drop_postgresql_database requires `packaging.version.Version`, You;d need to pass the version through `pkg_resources.parse_version` function actually.

**Comment by revmischa** [comment]
okay that worked. very mysterious that this stopped working all of a sudden.

**Comment by fizyk** [comment]
there's no mystery behind that :)

Wherever I can I'm moving to comparing packaging.version.Version objects not arbitrary floats ortuples, as this object encompasses comparing with pre and post releases as well.

And in the course of prepring 2.0.0 I introduced same change in `pytest-postgresql`
https://github.com/ClearcodeHQ/pytest-postgresql/commit/481283416da64eda4e7cca5252a30d07d0ede3e9#diff-414b36bde96cc5ac1b891480367a2ffe

Hadn't occurred to me that this function will be used for anything more than internal call, that's why I haven't mentioned it in the changelog. Otherwise that would be a separate commit with data type change alone ;)

**Comment by revmischa** [comment]
I'm using the setup described in the docs here - https://pypi.org/project/pytest-flask-sqlalchemy/#configuration

It works amazingly and is awesome. But I guess it's using secret features from this module?

**Comment by fizyk** [comment]
it's not secret features, just ones I haven't thought will be used outside ;)
I'm might gonna need to rework that, and produce some internal casting to compare....

**Comment by fizyk** [comment]
#226
