### ISSUE TITLE
The port_for module may be dead.....

### ISSUE THREAD

**Issue by jcpunk** [ClearcodeHQ/pytest-postgresql#347]
### What action do you want to perform
It is unclear how activly maintained the port_for is at this time:

https://github.com/kmike/port-for/pull/11

### What are the results

The port selection code may stop working with a future version of python

### What are the expected results

This is just an informational notice so folks can begin thinking.

**Comment by fizyk** [comment]
It would be best if there'd be an active alternative though. I don't think I'll find the spare time to maintain another library :)

**Comment by timok90** [comment]
Hey everybody,

I'm new to this module, so I might just make a mistake on usage.

I made the following simple test to get used with the syntax.
```
import tempfile
import os

# Third party imports
import pytest
import psycopg2
from pytest_postgresql import factories
import pytest_postgresql

from Datalogger.data_collect import DataLogger

# Using the factory to create a postgresql instance
socket_dir = tempfile.TemporaryDirectory()
postgresql_my_proc = factories.postgresql_proc(port=None,
                                               unixsocketdir=socket_dir.name)
postgresql_my = factories.postgresql('postgresql_my_proc')

@pytest.fixture(scope='function')
def setup_database(postgresql_my):
    def dbcreator():
        return postgresql_my.cursor().connection

    connection = dbcreator()
    yield connection
    connection.close()


@pytest.mark.dl
def test_example_postgres(setup_database):
    """Check main postgresql fixture."""
    conn = setup_database
    cur = conn.cursor()
    cur.execute(
        "CREATE TABLE test (id serial PRIMARY KEY, num integer, data varchar);"
    )
    conn.commit()
    cur.close()
    assert 0 == 0
```

I get following error and cant solve it. It seems for me as some submodule used by postgresql isn't working as expected:

\venv\lib\site-packages\port_for\api.py:27: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    for port in random.sample(ports, min(len(ports), 100)):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================================= short test summary info ================================================================================================= 
ERROR test_data_collect.py::test_example_postgres - port_for.exceptions.PortForException: Can't select a port

**Comment by fizyk** [comment]
@timok90 can you disable the warinings in your code? OR ignore that specific one?
I see that the port_for would have to be addressed sooner rather than later

**Comment by fizyk** [comment]
revived
