### ISSUE TITLE
psycopg 3 support

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-postgresql#485]
psycopg3 got released

Test and make sure pytest-postgresql supports it.
https://pypi.org/project/psycopg/

**Comment by mivade** [comment]
Hi, just chiming in here that still supporting psycopg2 would be nice since many libraries (e.g., peewee) that interact with Postgres do not yet support psycopg3. I've had to pin a number of tests to the last major release of pytest-postgresql to avoid conflicts. Luckily I have not encountered any issues where I might want the latest release but perhaps in the future new features or bug fixes may get missed because of this.

Thank you for this fantastic plugin!

**Comment by fizyk** [comment]
@mivade if it comes to fixing, issues in a pre 4.x version, We're open to, we'll create a 3.x branch that will be used to maintain bugfixes for the code supporting psycopg2. 
I just don't think we'll have the capacity to support both psycopg2 and psycopg3 in the same codebase. Speaking of which I too await for the support of psycopg3 in SQLAlchemy for one project ;) 

Although... Please check if you can install both psycopg2 and psycopg3 at the same time. psycopg3 is used by the plugin to initialize and manage the connection for the test code, and you should be able to use anything even pg8000 for the tested code.

**Comment by mmaslowskicc** [comment]
In a single project, I have psycopg2 for Alembic and SQLAlchemy in tests, psycopg (3) for pytest-postgresql and asyncpg for SQLAlchemy.

**Comment by mivade** [comment]
@fizyk interesting, I hadn't even though about seeing if both would work at the same time. I'll give that a shot. @mmaslowskicc gives me more confidence that that approach could work. Thank you both for your quick replies!
