### ISSUE TITLE
Does pytest-postgresql support parallel testing framework like pytest-xdist?

### ISSUE THREAD

**Issue by MagicFrogSJTU** [ClearcodeHQ/pytest-postgresql#699]
Does pytest-postgresql support some parallel testing framework like pytest-xdist?
When run in parallel, will pytest-postgresql actually using the same temporary database?

**Comment by fizyk** [comment]
@MagicFrogSJTU Yes and No.

Pytest-postgresql will not use, by default, the same temporary database, since this would influence other tests. In the standard run, it'll start a separate process per test thread, running on different ports.

unless you'd configure it using the no-process fixtures to connect to an already existing database... I have to admit, I haven't tested this case.

**Comment by MagicFrogSJTU** [comment]
> @MagicFrogSJTU Yes and No.
> 
> Pytest-postgresql will not use, by default, the same temporary database, since this would influence other tests. In the standard run, it'll start a separate process per test thread, running on different ports.
> 
> unless you'd configure it using the no-process fixtures to connect to an already existing database... I have to admit, I haven't tested this case.

So it is yes. Thank u very much!
